### ISSUE TITLE
The flutter pub run flutter_launcher_icons:main command is incorrect.

### ISSUE THREAD

**Issue by xiechunyan** [franzsilva/flutter_launcher_icons#11]
When I run "flutter pub run flutter_launcher_icons:main", the error message is as follows:
Error on line 97, column 6 of pubspec.yaml: A dependency may only have one source.
     image_path: "images/icon.png"
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pub finished with exit code 65

My pubspec. yaml file is configured as follows:
  flutter_launcher_icons: ^0.2.0
  flutter_icons:
     image_path: "images/icon.png"
     android: true
     ios: "Example-Icon"
How can I solve this problem?

**Comment by franzsilva** [comment]
hi @xiechunyan , are you properly indenting the file?,

**Comment by xiechunyan** [comment]
The previous error was caused by indent, and now the correct indent is reported as follows: 
Unhandled exception:
Error on line 2, column 15: Unexpected character.
description: é¿æ
              ^
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader._loadMapping (package:yaml/src/loader.dart:171:23)
#2      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#3      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#4      Loader.load (package:yaml/src/loader.dart:54:20)
#5      loadYamlDocument (package:yaml/yaml.dart:51:25)
#6      loadYamlNode (package:yaml/yaml.dart:42:5)
#7      loadYaml (package:yaml/yaml.dart:34:5)
#8      YamlConfigParser.parse (package:dart_config/parsers/config_parser_yaml.dart:13:15)
#9      Config.readConfig.<anonymous closure> (package:dart_config/config.dart:44:25)
#10     _RootZone.runUnary (dart:async/zone.dart:1381)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#14     _Future._completeWithValue (dart:async/future_impl.dart:477)
#15     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
pub finished with exit code 255

How can I solve this problem?

**Comment by xiechunyan** [comment]
I've found the reason, thank you.

**Comment by MarkOSullivan94** [comment]
@franzsilva / @xiechunyan  can one of you close this issue.

**Comment by g-balas** [comment]
> und the reason, thank you.

Thanks for telling us...

**Comment by Calvin92** [comment]
@xiechunyan So, how to fix it?  I got the same issue.

**Comment by MarkOSullivan94** [comment]
@Calvin92 paste your pubspec.yaml with the exact indentation here

**Comment by Stnieder** [comment]
Awesome solution...

**Comment by Stnieder** [comment]
After posting, I've found the solution by myself. And now my pubspec.yaml looks like this.
```
name: ProjectName
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_launcher_icons: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/time2eat.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```

After that editing I ran `flutter clean` and `flutter pub pub run flutter_launcher_icons:main`
