### ISSUE TITLE
busted on ios, with SWIFT it seems...

### ISSUE THREAD

**Issue by gedw99** [franzsilva/flutter_launcher_icons#21]
maybe i am doing something wrong ?

steps to repro

```
from an empty folder:
1. flutter create --org com.gedw99 --template=plugin -i swift -a kotlin hello
2. setup the pubspec.yaml as below
3. make icons and run
	# makes icons
	mkdir -p hello/example/icon
	cp icon/icon.png hello/example/icon
	cd hello/example && flutter pub get
	cd hello/example && flutter pub pub run flutter_launcher_icons:main

````

pubspec.yaml:
````

name: hello_example
description: Demonstrates how to use the hello plugin.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hello:
    path: ../
    
  flutter_launcher_icons: "^0.2.1"

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages


````

Output of make ft-icon:
````
x-MacBook-Pro:flutter apple$ make ft-icon
# fed: https://pub.dartlang.org/packages/flutter_launcher_icons
# copy code into the example/pubspec (see the icons.md)
# makes icons
mkdir -p hello/example/icon
cp icon/icon.png hello/example/icon
cd hello/example && flutter pub get
Running "flutter packages get" in example...                 0.9s
cd hello/example && flutter pub pub run flutter_launcher_icons:main
Saving new icon to ic_launcher.png and switching Android launcher icon to it
Overwriting default iOS launcher icon with new icon
Finished!
x-MacBook-Pro:flutter apple$ make ft-run-ios
open -a Simulator.app
cd hello/example && flutter run
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Skipping compilation. Fingerprint match.
Starting Xcode build...
 ├─Assembling Flutter resources...                    2.2s
 └─Compiling, linking and signing...                  3.9s
Xcode build done.                                            8.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference”logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /* com.apple.actool.errors */
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets: error: None of the input catalogs contained a matching stickers icon set or app icon set named  "Icon-App".
    /* com.apple.actool.document.warnings */
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/(null)[2d][Icon-App-60x60@1x.png]: warning: The app icon set "AppIcon" has an unassigned child.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][20x20][][][3x][][]: warning: AppIcon.appiconset/Icon-App-20x20@3x.png is 60x106 but should be 60x60.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][29x29][][][2x][][]: warning: AppIcon.appiconset/Icon-App-29x29@2x.png is 58x103 but should be 58x58.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][76x76][][][2x][][]: warning: AppIcon.appiconset/Icon-App-76x76@2x.png is 152x270 but should be 152x152.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][40x40][][][2x][][]: warning: AppIcon.appiconset/Icon-App-40x40@2x.png is 80x142 but should be 80x80.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][40x40][][][2x][][]: warning: AppIcon.appiconset/Icon-App-40x40@2x.png is 80x142 but should be 80x80.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][29x29][][][1x][][]: warning: AppIcon.appiconset/Icon-App-29x29@1x.png is 29x51 but should be 29x29.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][20x20][][][2x][][]: warning: AppIcon.appiconset/Icon-App-20x20@2x.png is 40x71 but should be 40x40.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][40x40][][][3x][][]: warning: AppIcon.appiconset/Icon-App-40x40@3x.png is 120x213 but should be 120x120.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][29x29][][][3x][][]: warning: AppIcon.appiconset/Icon-App-29x29@3x.png is 87x154 but should be 87x87.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][60x60][][][3x][][]: warning: AppIcon.appiconset/Icon-App-60x60@3x.png is 180x319 but should be 180x180.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][20x20][][][1x][][]: warning: AppIcon.appiconset/Icon-App-20x20@1x.png is 20x35 but should be 20x20.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][20x20][][][2x][][]: warning: AppIcon.appiconset/Icon-App-20x20@2x.png is 40x71 but should be 40x40.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][40x40][][][1x][][]: warning: AppIcon.appiconset/Icon-App-40x40@1x.png is 40x71 but should be 40x40.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][29x29][][][2x][][]: warning: AppIcon.appiconset/Icon-App-29x29@2x.png is 58x103 but should be 58x58.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][29x29][][][1x][][]: warning: AppIcon.appiconset/Icon-App-29x29@1x.png is 29x51 but should be 29x29.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][83.5x83.5][][][2x][][]: warning: AppIcon.appiconset/Icon-App-83.5x83.5@2x.png is 167x296 but should be 167x167.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][iphone][60x60][][][2x][][]: warning: AppIcon.appiconset/Icon-App-60x60@2x.png is 120x213 but should be 120x120.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ipad][76x76][][][1x][][]: warning: AppIcon.appiconset/Icon-App-76x76@1x.png is 76x135 but should be 76x76.
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/ios/Runner/Assets.xcassets:./AppIcon.appiconset/[][ios-marketing][1024x1024][][][1x][][]: warning: AppIcon.appiconset/Icon-App-1024x1024@1x.png is 1024x1819 but should be 1024x1024.
    /* com.apple.actool.compilation-results */
    /Users/apple/workspace/go/src/bitbucket.org/gedw99/md-flutter/sdk/ci/flutter/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Assets.car
    /Users/apple/Library/Developer/Xcode/DerivedData/Runner-dtbkweoretbigafrvarnpjyccwxb/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/assetcatalog_generated_info.plist

Could not build the application for the simulator.
Error launching application on iPhone 8 Plus.
make: *** [ft-run-ios] Error 2

````
