### ISSUE TITLE
 android: true ?

### ISSUE THREAD

**Issue by Solido** [franzsilva/flutter_launcher_icons#38]
flutter_launcher_icons: "^0.5.2"
  flutter_icons:
    android: true
    ios: "Select-Icon"
    image_path: "assets/Select.png"
    #image_path_android: "assets/icon/icon_android.png"
    #image_path_ios: "assets/icon/icon_ios.png"
    adaptive_icon_background: "#FFFAFAFA"
    #adaptive_icon_foreground: "assets/icon/icon-foreground.png"

flutter pub pub run flutter_launcher_icons:main
Error on line 54, column 5 of pubspec.yaml: A dependency may only have one source.
    android: true
    ^^^^^^^^^^^^^^
pub finished with exit code 65

**Comment by ffeu** [comment]
just checking.. did you place flutter_launcher_icons inside dev_dependencies and respected the indentation?

```
dev_dependencies:
  flutter_launcher_icons: "^0.5.2"
  flutter_test:
    sdk: flutter

# ... the other lines in your file ...

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"
```
