### ISSUE TITLE
Ability to name the icon

### ISSUE THREAD

**Issue by gaara87** [franzsilva/flutter_launcher_icons#6]
It would be nice if you can provide a command line argument which will to take in the file name to produce

**Comment by MarkOSullivan94** [comment]
@gaara87 why are you looking to change the icon name? 

Do you not want the icon to replace the existing launcher icon? 

Or is it because you'd want to have seasonal icons and so anytime you run the tool with a new icon name, you want both apps to switch to the icon name specified but retain the old one?

**Comment by gaara87** [comment]
Definitely the latter. Jus having the option to call it something besides
ic_launcher makes it easier to identify it also if we have multiple ones.

It needn't even be seasonal, it can be a daily thing also :) but yes.

**Comment by franzsilva** [comment]
Changing the file name would involve also modifying the underlying platforms iOS & Android so that it can point to the new filename. I would suggest having a folder with multiple icons and the types of icons you would like to have. then in the pubspect config we could read a parameter with the name of the icon and replace the icons needed. 

So basically we could have a parameter in the pupspec file like

```yaml
flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: false
  custom:
    icon1:  "icon/icon1.png"
    icon2:  "icon/icon2.png"
    icon3:  "icon/icon3.png"
```
Then we can add an optional parameter to specify the icon name to use like:

`flutter pub pub run flutter_launcher_icons:main icon3`

then we would use that icon specified on the command. 

This would allow to quickly swap the icons. 

What do you think?
