### ISSUE TITLE
Metadata in a separate file

### ISSUE THREAD

**Issue by gaara87** [franzsilva/flutter_launcher_icons#7]
Let this be in a separate file
```
icon_spec.yaml
  image_path: "icon/icon.png" 
  android: true
  ios: false

flutter_icons:
  config: "icon_spec.yaml"
```
