### ISSUE TITLE
ios icon not being generated and no error

### ISSUE THREAD

**Issue by gedw99** [franzsilva/flutter_launcher_icons#8]
android works.
but not ios.

anyone else getting this ?

from project root calling:
flutter pub pub run flutter_launcher_icons:main

---

pubspec.yaml
````

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.0.1"

flutter_icons:
  image_path: "icon.png" 
  android: true
  ios: true

````

---
